# Generated by Django 2.1 on 2021-10-11 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('geometry', models.CharField(choices=[('PMB', 'Precious Metal'), ('BMB', 'Base Metal'), ('SG', 'Special Grant'), ('SB', 'Special Block')], max_length=50)),
                ('mining_claim', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartMineMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('valid', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('resource_size', models.IntegerField()),
                ('resource_unit', models.CharField(choices=[('Tonnes', 'Metric Tonnes'), ('Ounces', 'Ounces')], max_length=30)),
                ('min_grade', models.IntegerField()),
                ('grade_unit', models.CharField(choices=[('Kgs/Tonne', 'Kgs Per Tonne'), ('Grams/Tonne', 'Grams Per Tonne'), ('Ounces/Tonne', 'Ounces Per Tonne')], max_length=30)),
                ('invest_type', models.CharField(choices=[('Purchase', 'Purchase'), ('JV', 'Joint-Venture'), ('Tribute', 'Tribute'), ('Manage', 'Raising Contract')], max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRegCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('Pvt Ltd', 'Private (Limited)'), ('Ltd', 'Public'), ('PBC', 'PBC')], max_length=20)),
                ('dor', models.DateField(verbose_name='Date of Registration')),
                ('agents', models.ManyToManyField(related_name='agent_user', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Zimbabwe', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Corporate')),
            ],
        ),
        migrations.CreateModel(
            name='EngReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('report_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('digital', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnvMgtReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('report_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('digital', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExplStoCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExplTrnsCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('cost', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under-Way', 'Under-Way'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldProforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('period', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Proforma', 'Proforma'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeoReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('report_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('digital', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncorpCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Corporate')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('pid', models.CharField(max_length=255, verbose_name='Personal Identity Doc')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('nid', models.CharField(max_length=50, verbose_name='Identity Number')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Country')),
            ],
        ),
        migrations.CreateModel(
            name='InspecCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('valid', models.DateField()),
                ('payment', models.FloatField()),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Under-Way', 'Under-Way'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MandateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('period', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cart_mine_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.CartMineMatch')),
            ],
        ),
        migrations.CreateModel(
            name='MetReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('report_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('digital', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('insp_date', models.DateField(verbose_name='Last Inspected')),
                ('reserves_proven', models.IntegerField(null=True)),
                ('reserves_possible', models.IntegerField(null=True)),
                ('reserves_probable', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Cart', 'Cart'), ('Field', 'Field'), ('Mandate', 'Mandate')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MineEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_employed', models.DateField(null=True)),
                ('post', models.CharField(choices=[('Chief', 'Chief'), ('Snr', 'Senior'), ('Ass', 'Assistant'), ('Jnr', 'Juniour'), ('Snr', 'Senior'), ('Skilled', 'Skilled'), ('Semi Skilled', 'Semi Skilled')], max_length=30)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='MineJobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MineMgrCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine')),
            ],
        ),
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiningClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('reg_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PMB', 'Precious Metal'), ('BMB', 'Base Metal'), ('SG', 'Special Grant'), ('SB', 'Special Block')], max_length=50)),
                ('reg_number', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine')),
            ],
        ),
        migrations.CreateModel(
            name='NonEncumbCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine')),
            ],
        ),
        migrations.CreateModel(
            name='PersId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate'), ('Syndicate', 'Syndicate'), ('Prof Service', 'Prof Service'), ('Advertiser', 'Advertiser'), ('Advertiser', 'Advertiser'), ('MC', 'Mining Connect')], max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('bank', models.CharField(max_length=100, null=True)),
                ('bank_account', models.CharField(max_length=50, null=True)),
                ('street_address', models.CharField(max_length=100)),
                ('trxn_balance', models.FloatField(default=0)),
                ('suburb', models.CharField(max_length=100, verbose_name='Surburb / Zip Code')),
                ('city', models.CharField(max_length=100, verbose_name='Town / City')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Country', verbose_name='Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='ProdReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('report_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('digital', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine')),
            ],
        ),
        migrations.CreateModel(
            name='ProfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='SerProvProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('engagement', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('ref_contact', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('report_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('digital', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine')),
            ],
        ),
        migrations.CreateModel(
            name='SyndAgree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('pdf', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Syndicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('dor', models.DateField(verbose_name='Date of Creation')),
                ('agents', models.ManyToManyField(related_name='syndicate_agent_user', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to='mine.IndRecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player')),
            ],
        ),
        migrations.CreateModel(
            name='TrxnPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trxns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trxns_payee', to='mine.Player')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.TrxnPurpose')),
            ],
        ),
        migrations.AddField(
            model_name='syndagree',
            name='syndicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Syndicate'),
        ),
        migrations.AddField(
            model_name='serviceprov',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.ServiceProvRole'),
        ),
        migrations.AddField(
            model_name='serviceprov',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.ProfService'),
        ),
        migrations.AddField(
            model_name='serprovprofile',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.ServiceProv'),
        ),
        migrations.AddField(
            model_name='serprovprofile',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player'),
        ),
        migrations.AddField(
            model_name='serprovprofile',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Individual'),
        ),
        migrations.AddField(
            model_name='serprovprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.ServiceProvRole'),
        ),
        migrations.AddField(
            model_name='mineemployees',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.MineJobList'),
        ),
        migrations.AddField(
            model_name='mineemployees',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='mine',
            name='mineral',
            field=models.ManyToManyField(to='mine.Mineral'),
        ),
        migrations.AddField(
            model_name='mine',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player'),
        ),
        migrations.AddField(
            model_name='mine',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.DepositType'),
        ),
        migrations.AddField(
            model_name='metreport',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='mandaterequest',
            name='mines',
            field=models.ManyToManyField(to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='mandate_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.MandateRequest'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='mine',
            field=models.ManyToManyField(to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.TrxnPurpose'),
        ),
        migrations.AddField(
            model_name='investor',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player'),
        ),
        migrations.AddField(
            model_name='inspeccert',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='individual',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player'),
        ),
        migrations.AddField(
            model_name='georeport',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='fieldreq',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mandate'),
        ),
        migrations.AddField(
            model_name='fieldreq',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='fieldreq',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.ProfService'),
        ),
        migrations.AddField(
            model_name='fieldproforma',
            name='field_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mandate'),
        ),
        migrations.AddField(
            model_name='fieldinvoice',
            name='field_proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_proforma', to='mine.Invoice'),
        ),
        migrations.AddField(
            model_name='fieldinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Invoice'),
        ),
        migrations.AddField(
            model_name='field',
            name='mine_owner_requirements',
            field=models.ManyToManyField(to='mine.MineJobList'),
        ),
        migrations.AddField(
            model_name='field',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.FieldProforma'),
        ),
        migrations.AddField(
            model_name='field',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.ServiceProv'),
        ),
        migrations.AddField(
            model_name='expltrnscert',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='explstocert',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='envmgtreport',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='engreport',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='corporate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player'),
        ),
        migrations.AddField(
            model_name='claimregcert',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.MiningClaim'),
        ),
        migrations.AddField(
            model_name='cartrequest',
            name='deposit_type',
            field=models.ManyToManyField(to='mine.DepositType'),
        ),
        migrations.AddField(
            model_name='cartrequest',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Investor'),
        ),
        migrations.AddField(
            model_name='cartrequest',
            name='mineral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mineral'),
        ),
        migrations.AddField(
            model_name='cartminematch',
            name='cart_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.CartRequest'),
        ),
        migrations.AddField(
            model_name='cartminematch',
            name='mines',
            field=models.ManyToManyField(to='mine.Mine'),
        ),
    ]
