# Generated by Django 2.1 on 2021-10-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0002_auto_20211018_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartminematch',
            name='mines',
            field=models.ManyToManyField(through='mine.CartMineRelation', to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='mine',
            field=models.ManyToManyField(through='mine.MineMandateRelation', to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='mandaterequest',
            name='mines',
            field=models.ManyToManyField(through='mine.MineMandateRequest', to='mine.Mine'),
        ),
        migrations.AddField(
            model_name='mine',
            name='mineral',
            field=models.ManyToManyField(through='mine.MineMineral', to='mine.Mineral'),
        ),
    ]
