# Generated by Django 2.1 on 2021-10-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0003_auto_20211018_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyndAgentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Suspended', 'Suspended'), ('Current', 'Currrent'), ('Active', 'Active')], default='Current', max_length=30)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.IndRecord')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyndMemberRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Suspended', 'Suspended'), ('Current', 'Currrent'), ('Active', 'Active')], default='Current', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.IndRecord')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartrequest',
            name='resource_size',
        ),
        migrations.RemoveField(
            model_name='mine',
            name='claims',
        ),
        migrations.RemoveField(
            model_name='syndicate',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='syndicate',
            name='members',
        ),
        migrations.AddField(
            model_name='cartrequest',
            name='valid',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='trxn_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mine.Trxns'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartrequest',
            name='grade_unit',
            field=models.CharField(choices=[('Kgs/Tonne', 'Kgs Per Tonne'), ('Grams/Tonne', 'Grams Per Tonne'), ('Ounces/Tonne', 'Ounces Per Tonne'), ('%', '%')], max_length=30),
        ),
        migrations.AddField(
            model_name='syndmemberrelation',
            name='syndicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Syndicate'),
        ),
        migrations.AddField(
            model_name='syndagentrelation',
            name='syndicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Syndicate'),
        ),
    ]
