# Generated by Django 2.1 on 2021-10-27 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0004_auto_20211027_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='syndicate',
            name='agents',
            field=models.ManyToManyField(related_name='syndicate_agent_user', through='mine.SyndAgentRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='members',
            field=models.ManyToManyField(through='mine.SyndMemberRelation', to='mine.IndRecord'),
        ),
    ]
