# Generated by Django 2.1 on 2021-10-27 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0005_auto_20211027_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpAgentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Suspended', 'Suspended'), ('Current', 'Currrent'), ('Active', 'Active')], default='Current', max_length=30)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.IndRecord')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='corprecord',
            name='agents',
        ),
        migrations.AddField(
            model_name='corpagentrelation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.CorpRecord'),
        ),
    ]
