# Generated by Django 2.1 on 2021-11-02 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0007_corprecord_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldActivityQoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Supplied Quote', 'Supplied Quote'), ('Winning', 'Winning')], default='Pending', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('Technical', 'Technical'), ('Receipts', 'Receipts')], max_length=15)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='field',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.ServiceProv'),
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Qoutation', 'Qoutation'), ('Under-Way', 'Under-Way'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=15),
        ),
        migrations.AddField(
            model_name='fieldattachments',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Field'),
        ),
        migrations.AddField(
            model_name='fieldattachments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldactivityqoutes',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.Field'),
        ),
        migrations.AddField(
            model_name='fieldactivityqoutes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldactivityqoutes',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_proforma', to='mine.ServiceProv'),
        ),
    ]
