# Generated by Django 2.1 on 2021-11-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0009_auto_20211123_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trxns',
            name='balance',
        ),
        migrations.AlterField(
            model_name='playeruserrelation',
            name='status',
            field=models.CharField(choices=[('Non Active', 'Non Active'), ('Active', 'Active')], default='Active', max_length=30),
        ),
    ]
