# Generated by Django 2.1 on 2021-11-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0011_auto_20211124_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='corprecord',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Done', 'Done')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='indrecord',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Done', 'Done')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Done', 'Done')], default='None', max_length=10),
        ),
    ]
