# Generated by Django 2.1 on 2021-11-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0012_auto_20211124_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruserrelation',
            name='investor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playeruserrelation',
            name='mine_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playeruserrelation',
            name='service_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corprecord',
            name='type',
            field=models.CharField(choices=[('Pvt Ltd', '(Private) Limited'), ('Ltd', 'Public'), ('PBC', 'PBC')], max_length=20),
        ),
    ]
