# Generated by Django 2.1 on 2021-11-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0013_auto_20211125_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='insp_status',
            field=models.CharField(choices=[('Current', 'Current'), ('Tributed', 'Tributed'), ('Sold', 'Sold'), ('Forfeited', 'Forfeited')], default='Free', max_length=20),
        ),
    ]
