# Generated by Django 2.1 on 2021-11-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0014_mine_insp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='geometry',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
