# Generated by Django 2.1 on 2021-11-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0015_auto_20211126_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minereports',
            name='digital',
        ),
        migrations.AlterField(
            model_name='minecertificates',
            name='pdf',
            field=models.ImageField(null=True, upload_to='images/reports/'),
        ),
        migrations.AlterField(
            model_name='minereports',
            name='pdf',
            field=models.ImageField(null=True, upload_to='images/reports/'),
        ),
    ]
