# Generated by Django 2.1 on 2021-11-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0016_auto_20211127_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimregcert',
            name='pdf',
            field=models.ImageField(null=True, upload_to='images/reports/'),
        ),
    ]
