# Generated by Django 2.1 on 2021-12-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0020_auto_20211130_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruserrelation',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
