# Generated by Django 2.1 on 2021-12-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0021_playeruserrelation_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
