# Generated by Django 2.1 on 2021-12-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0023_cartrequest_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='type',
            field=models.CharField(choices=[('Inter-mediate', 'mediate'), ('Corner', 'Corner')], default='Inter-mediate', max_length=15),
        ),
    ]
