# Generated by Django 2.1 on 2021-12-05 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0024_beacon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorMineRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Cart', 'Cart'), ('Mandate-Request', 'Mandate-Request'), ('Mandate', 'Mandate'), ('Free', 'Free')], default='Cart', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Investor')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Mine')),
            ],
        ),
        migrations.AlterField(
            model_name='beacon',
            name='type',
            field=models.CharField(choices=[('Inter-mediate', 'Inter-mediate'), ('Corner', 'Corner')], default='Inter-mediate', max_length=15),
        ),
    ]
