# Generated by Django 2.1 on 2021-12-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0025_auto_20211205_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorminerelation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='investorminerelation',
            name='date_created',
        ),
    ]
