# Generated by Django 2.1 on 2021-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0026_auto_20211205_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorminerelation',
            name='valid',
            field=models.DateField(null=True),
        ),
    ]
