# Generated by Django 2.1 on 2021-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0027_investorminerelation_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorminerelation',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
