# Generated by Django 2.1 on 2021-12-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0029_auto_20211206_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandaterequest',
            name='mines',
        ),
        migrations.AddField(
            model_name='mandaterequest',
            name='mine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mine.Mine'),
            preserve_default=False,
        ),
    ]
