# Generated by Django 2.1 on 2021-12-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0030_auto_20211207_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under-Way', 'Under-Way'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='minemandaterelation',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Desktop', 'Desktop'), ('Field', 'Field'), ('Exclusive Option', 'Exclusive Option'), ('Negotiation', 'Negotiation'), ('Success', 'Success')], default='Current', max_length=30),
        ),
    ]
