# Generated by Django 2.1 on 2021-12-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0032_auto_20211207_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minemandaterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Proforma', 'Proforma'), ('Failed', 'Failed'), ('Complete', 'Complete')], default='Pending', max_length=30),
        ),
    ]
