# Generated by Django 2.1 on 2021-12-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0034_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningclaim',
            name='area',
            field=models.FloatField(blank=True, default=100),
            preserve_default=False,
        ),
    ]
