# Generated by Django 2.1 on 2021-12-08 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0036_auto_20211208_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mine.Country'),
            preserve_default=False,
        ),
    ]
