# Generated by Django 2.1 on 2021-12-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0037_mine_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineinvestreq',
            name='conglomerate',
            field=models.BooleanField(default=False),
        ),
    ]
