# Generated by Django 2.1 on 2021-12-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0038_mineinvestreq_conglomerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandaterequest',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('JV', 'Joint-Venture'), ('Tribute', 'Tribute'), ('Manage', 'Raising Contract')], default='Purchase', max_length=100),
        ),
    ]
