# Generated by Django 2.1 on 2021-12-08 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0039_auto_20211208_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandaterequest',
            name='purpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mine.MandateTypeList'),
            preserve_default=False,
        ),
    ]
