# Generated by Django 2.1 on 2021-12-08 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0041_mandaterequest_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateProforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Quotation', 'Quotation'), ('Active', 'Active')], default='Pending', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mandate_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.MandateRequest')),
            ],
        ),
    ]
