# Generated by Django 2.1 on 2021-12-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0042_mandateproforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('Mine-Owner', 'Mine-Owner'), ('Investor', 'Investor'), ('Service Provider', 'Service Provider')], max_length=100)),
                ('sub', models.CharField(choices=[('Subs', 'Subs'), ('On boarding', 'On boarding'), ('Fees', ' Fees')], max_length=30)),
                ('amount', models.FloatField()),
                ('period', models.CharField(choices=[('Week', 'Week'), ('Month', 'Month'), ('Quarter', 'Quarter'), ('Annual', 'Annual')], max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
