# Generated by Django 2.1 on 2021-12-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0043_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandateproforma',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
    ]
