# Generated by Django 2.1 on 2021-12-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0047_auto_20211209_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='field_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.FieldReq'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.Mandate'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mandate_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.MandateRequest'),
        ),
    ]
