# Generated by Django 2.1 on 2021-12-10 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0049_auto_20211209_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.Player')),
            ],
        ),
    ]
