# Generated by Django 2.1 on 2021-12-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0050_playercash'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercash',
            name='ref',
            field=models.CharField(default='Cash', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trxns',
            name='reverse_trxn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
