# Generated by Django 2.1 on 2021-12-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0051_auto_20211210_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='payment_status',
        ),
    ]
