# Generated by Django 2.1 on 2021-12-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0052_auto_20211210_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Desktop', 'Desktop'), ('Field', 'Field'), ('Exclusive Option', 'Exclusive Option'), ('Negotiation', 'Negotiation'), ('Success', 'Success')], default='Desktop', max_length=30),
        ),
    ]
