# Generated by Django 2.1 on 2021-12-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0053_mandate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mandaterequest',
            name='type',
        ),
        migrations.RemoveField(
            model_name='minemandaterelation',
            name='status',
        ),
        migrations.AddField(
            model_name='mandate',
            name='mine',
            field=models.ManyToManyField(through='mine.MineMandateRelation', to='mine.Mine'),
        ),
        migrations.AlterField(
            model_name='minemandaterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Proforma', 'Proforma'), ('Mandate', 'Mandate'), ('Failed', 'Failed'), ('Complete', 'Complete')], default='Pending', max_length=30),
        ),
    ]
