# Generated by Django 2.1 on 2021-12-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0054_auto_20211211_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldreq',
            name='mine',
        ),
        migrations.AddField(
            model_name='fieldproforma',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fieldproforma',
            name='quote_providers',
            field=models.ManyToManyField(through='mine.FieldProviderQuote', to='mine.ServiceProv'),
        ),
    ]
