# Generated by Django 2.1 on 2021-12-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0055_auto_20211213_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercertificates',
            name='pdf',
        ),
        migrations.AddField(
            model_name='fieldreq',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='fieldreq',
            name='pdf',
            field=models.ImageField(null=True, upload_to='images/reports/'),
        ),
    ]
