# Generated by Django 2.1 on 2021-12-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0057_playercertificates_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='fieldreq',
            name='service_req',
            field=models.BooleanField(default=False, verbose_name='Service Providers Required?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovrequired',
            name='field_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.FieldReq'),
        ),
        migrations.AddField(
            model_name='serviceprovrequired',
            name='provider_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.ServiceProvRole'),
        ),
    ]
