# Generated by Django 2.1 on 2021-12-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0060_serviceprovrequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreq',
            name='provider_roles',
            field=models.ManyToManyField(through='mine.ServiceProvRequired', to='mine.ServiceProvRole'),
        ),
    ]
