# Generated by Django 2.1 on 2021-12-16 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0062_auto_20211216_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mine.ProfService')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldReqWinQte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldSupCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.FieldCostList')),
                ('field_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.FieldReq')),
            ],
        ),
        migrations.RemoveField(
            model_name='fieldproforma',
            name='quote_providers',
        ),
        migrations.AddField(
            model_name='fieldproforma',
            name='provider_costs',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldproviderquote',
            name='service_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.ServiceProvRequired'),
        ),
        migrations.AddField(
            model_name='fieldreqwinqte',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.FieldProviderQuote'),
        ),
        migrations.AddField(
            model_name='fieldreqwinqte',
            name='service_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.ServiceProvRequired'),
        ),
        migrations.AddField(
            model_name='fieldproforma',
            name='admin_premium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mine.AdminPremium'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldproforma',
            name='support_costs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mine.FieldSupCosts'),
            preserve_default=False,
        ),
    ]
