# Generated by Django 2.1 on 2021-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0063_auto_20211216_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsupcosts',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Quotation', 'Quotation'), ('Under-Way', 'Under-Way'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=15),
        ),
    ]
