# Generated by Django 2.1 on 2021-12-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0064_auto_20211216_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateOrgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Non Active', 'Non Active'), ('Active', 'Active')], default='Active', max_length=30)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.AffiliateOrgs')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='fieldproviderquote',
            name='proforma',
        ),
        migrations.AddField(
            model_name='serviceprovrequired',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fieldproforma',
            name='provider_costs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldproforma',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Quotation', 'Quotation'), ('Active', 'Active')], default='Pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fieldproforma',
            name='support_costs',
            field=models.FloatField(default=0),
        ),
    ]
