# Generated by Django 2.1 on 2022-01-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0070_auto_20220107_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='field',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='field',
            name='task',
            field=models.TextField(default='None', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under-Way', 'Under-Way'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=15),
        ),
    ]
