# Generated by Django 2.1 on 2022-01-08 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0071_auto_20220107_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiedlMineRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiedlProviderRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='field',
            name='mine_owner_requirements',
        ),
        migrations.AddField(
            model_name='fiedlproviderrelation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Field'),
        ),
        migrations.AddField(
            model_name='fiedlproviderrelation',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.ServiceProv'),
        ),
        migrations.AddField(
            model_name='fiedlminerequirements',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.Field'),
        ),
        migrations.AddField(
            model_name='fiedlminerequirements',
            name='required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.MineJobList'),
        ),
        migrations.AddField(
            model_name='field',
            name='provider',
            field=models.ManyToManyField(through='mine.FiedlProviderRelation', to='mine.ServiceProv'),
        ),
    ]
