# Generated by Django 2.1 on 2022-01-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0074_auto_20220111_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreq',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Service Choice', 'Service Choice'), ('Proforma', 'Proforma'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Field', 'Field')], max_length=15, null=True),
        ),
    ]
