# Generated by Django 2.1 on 2022-01-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0075_auto_20220111_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='subject',
            field=models.TextField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
