# Generated by Django 2.1 on 2022-01-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0076_field_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='subject',
        ),
    ]
