# Generated by Django 2.1 on 2022-01-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0077_remove_field_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='subject',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
