# Generated by Django 2.1 on 2022-01-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0080_auto_20220117_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimregcert',
            name='pdf',
            field=models.ImageField(null=True, upload_to='images/certificates/'),
        ),
        migrations.AddField(
            model_name='fieldproviderquote',
            name='pdf',
            field=models.ImageField(blank=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='fieldreq',
            name='pdf',
            field=models.ImageField(null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='minecertificates',
            name='pdf',
            field=models.ImageField(null=True, upload_to='images/certificates/'),
        ),
        migrations.AddField(
            model_name='mineemployees',
            name='pdf',
            field=models.ImageField(blank=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='minereports',
            name='pdf',
            field=models.ImageField(null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='playercertificates',
            name='pdf',
            field=models.ImageField(null=True, upload_to='images/certificates/'),
        ),
        migrations.AlterField(
            model_name='fieldattachments',
            name='pdf',
            field=models.ImageField(blank=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='workhistattach',
            name='pdf',
            field=models.ImageField(blank=True, upload_to='docs/'),
        ),
    ]
