# Generated by Django 2.1 on 2022-01-20 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0082_auto_20220119_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAcquit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('acquit', models.BooleanField(null=True)),
                ('comment', models.TextField(default='Complete', max_length=2000, verbose_name='Task Report')),
                ('recommendation', models.TextField(blank=True, max_length=2000, verbose_name='Mine Owner Recommendation')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.Field')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
