# Generated by Django 3.2.11 on 2022-01-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0083_fieldacquit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldacquit',
            name='recommendation',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Mine Recommendation'),
        ),
    ]
