# Generated by Django 3.2.11 on 2022-01-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0084_alter_fieldacquit_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldacquit',
            name='acquit',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
