# Generated by Django 3.2.11 on 2022-02-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0085_alter_fieldacquit_acquit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Urls',
            new_name='ServerIP',
        ),
        migrations.RenameField(
            model_name='serverip',
            old_name='url',
            new_name='name',
        ),
    ]
