# Generated by Django 3.2.11 on 2022-02-12 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0088_auto_20220211_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='player',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='sub_amount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='sub_period',
            field=models.CharField(choices=[('Quarter', 'Quarter'), ('Bi-Annual', 'Bi-Annual'), ('Annual', 'Annual')], default='Quarter', max_length=16),
        ),
        migrations.AddField(
            model_name='player',
            name='sub_type',
            field=models.CharField(choices=[('Mine Owner', 'Mine Owner'), ('Investor', 'Investor'), ('Service Provider', 'Service Provider'), ('Combination', 'Combination')], default='Mine Owner', max_length=16),
        ),
    ]
