# Generated by Django 3.2.11 on 2022-06-08 07:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0089_auto_20220212_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='beacon',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='beacon',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='beacon',
            name='longitude',
        ),
        migrations.AddField(
            model_name='beacon',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='cartrequest',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mine',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mine',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mineplant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mineworks',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='miningclaim',
            name='beacons',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='miningclaim',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='miningclaim',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Off', 'Off')], default='Active', max_length=15),
        ),
    ]
