# Generated by Django 3.2.11 on 2022-06-13 23:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0091_remove_mine_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
