# Generated by Django 3.2.11 on 2022-06-14 23:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0092_mine_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineworks',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mineworks',
            name='location',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
    ]
