# Generated by Django 3.2.11 on 2022-06-26 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0094_auto_20220615_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minelocation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mine_locations', to='mine.mine'),
        ),
    ]
