# Generated by Django 3.2.11 on 2022-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0096_country_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
