# Generated by Django 3.2.11 on 2022-08-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0097_alter_player_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacon',
            name='location',
        ),
        migrations.RemoveField(
            model_name='beacon',
            name='type',
        ),
        migrations.AddField(
            model_name='beacon',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beacon',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beacon',
            name='symbol',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
