# Generated by Django 3.2.11 on 2022-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0099_alter_miningclaimpolygon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
