# Generated by Django 3.2.11 on 2022-09-26 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0100_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Inspection', 'Inspection'), ('Registration', 'Registration'), ('Site', 'Site'), ('Explosives', 'Explosives'), ('Fine', 'Fine'), ('Other', 'Other')], max_length=50)),
                ('report_date', models.DateField(null=True)),
                ('rec_number', models.IntegerField()),
                ('pdf', models.FileField(null=True, upload_to='docs/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.mine')),
            ],
        ),
        migrations.CreateModel(
            name='MineLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('report_date', models.DateField(null=True)),
                ('other_party', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=4)),
                ('pdf', models.FileField(null=True, upload_to='docs/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.mine')),
            ],
        ),
        migrations.CreateModel(
            name='MineAgreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Tribute', 'Tribute'), ('Joint Venture', 'Joint Venture'), ('Management.', 'Management')], max_length=50)),
                ('counter_party', models.CharField(max_length=100)),
                ('report_date', models.DateField(null=True)),
                ('pdf', models.FileField(null=True, upload_to='docs/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.mine')),
            ],
        ),
    ]
