# Generated by Django 3.2.11 on 2022-09-28 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0101_mineagreements_mineletters_minereceipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineagreements',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mine.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mineletters',
            name='inout',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mineletters',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mine.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minereceipts',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mine.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mineagreements',
            name='mine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mine.mine'),
        ),
        migrations.AlterField(
            model_name='mineletters',
            name='mine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mine.mine'),
        ),
        migrations.AlterField(
            model_name='mineletters',
            name='type',
            field=models.CharField(choices=[('Mines Ministry', 'Mines Ministry'), ('Government', 'Government'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='minereceipts',
            name='mine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mine.mine'),
        ),
        migrations.CreateModel(
            name='OtherDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('report_date', models.DateField(null=True)),
                ('subject', models.CharField(max_length=500)),
                ('pdf', models.FileField(null=True, upload_to='docs/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mine.mine')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.player')),
            ],
        ),
    ]
