# Generated by Django 3.2.11 on 2022-10-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0102_auto_20220928_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecertificates',
            name='mine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.mine'),
        ),
        migrations.AlterField(
            model_name='minereports',
            name='mine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.mine'),
        ),
    ]
