# Generated by Django 3.2.11 on 2022-10-24 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0103_auto_20221025_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minemineral',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minemineral',
            name='mine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.mine'),
        ),
        migrations.AlterField(
            model_name='minemineral',
            name='mineral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.mineral'),
        ),
    ]
