# Generated by Django 3.2.11 on 2022-12-26 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0122_auto_20221225_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='assays',
            name='assay',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sampleassays',
            name='sample_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='samplepoint',
            name='mine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mine.mine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assays',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assays',
            name='mineral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mine.elements'),
        ),
        migrations.AddField(
            model_name='assays',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mine.assayunits'),
            preserve_default=False,
        ),
    ]
