# Generated by Django 3.2.11 on 2022-12-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0123_auto_20221226_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleassays',
            name='sample_date',
        ),
        migrations.AddField(
            model_name='assays',
            name='sample_date',
            field=models.DateField(null=True),
        ),
    ]
