# Generated by Django 3.2.11 on 2022-12-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0124_auto_20221226_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksimages',
            old_name='works',
            new_name='plant',
        ),
        migrations.AddField(
            model_name='mineyellowplant',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
