# Generated by Django 3.2.11 on 2022-12-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0127_auto_20221228_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimages',
            name='image',
            field=models.ImageField(null=True, upload_to='images/plant/'),
        ),
        migrations.AlterField(
            model_name='worksimages',
            name='image',
            field=models.ImageField(null=True, upload_to='images/works/'),
        ),
        migrations.AlterField(
            model_name='yellowimages',
            name='image',
            field=models.ImageField(null=True, upload_to='images/mobile_plant/'),
        ),
    ]
