# Generated by Django 3.2.11 on 2022-12-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0128_auto_20221228_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='phone_number',
        ),
    ]
