# Generated by Django 3.2.11 on 2022-12-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0129_remove_player_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone_number',
            field=models.CharField(default='1234561234567', max_length=14),
            preserve_default=False,
        ),
    ]
